version: "3"
services:
  saga-service:
    image: 10.229.54.39:8297/saga-service:1.0-dev-201908
    command: "-Duser.timezone=GMT+0 -jar /application.jar"
    ports:
      - "8302:8761"
    networks:
      - movitel
    environment:
      SPRING_APPLICATION_NAME: "saga-service"
      SERVER_PORT: "8761"
      SPRING_PROFILES_ACTIVE: "movitel"
    deploy:
      replicas: 5
networks:
  movitel:
    external: true
