package com.biplus.saga.domain.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Arrays;

public enum ActionType {
    UPDATE_LABOR_CONTRACT_HISTORY_CHANNEL("UPDATE_LABOR_CONTRACT_HISTORY_CHANNEL"),
    CANDIDATE_ASSIGN_CHANNEL("CANDIDATE_ASSIGN_CHANNEL"),
    SAVE_ONBOARD_STATUS("SAVE_ONBOARD_STATUS"),
    CREATE_EMPLOYEE_CHANNEL("CREATE_EMPLOYEE_CHANNEL"),
    SAVE_INTERVIEW_CONTACT_CHANNEL("SAVE_INTERVIEW_CONTACT_CHANNEL"),
    SAVE_INTERVIEW_SCHEDULE_CHANNEL("SAVE_INTERVIEW_SCHEDULE_CHANNEL"),
    APPROVAL_RECRUITMENT_PROPOSAL_CHANNEL("APPROVAL_RECRUITMENT_PROPOSAL_CHANNEL"),
    APPROVAL_RECRUITMENT_DECISION_CHANNEL("APPROVAL_RECRUITMENT_DECISION_CHANNEL"),
    INTERVIEW_EVALUATION_CHANNEL("INTERVIEW_EVALUATION_CHANNEL"),
    EMPLOYEE_CREATE_CHANNEL("EMPLOYEE_CREATE_CHANNEL"),
    EMPLOYEE_APPROVAL_CHANNEL("EMPLOYEE_APPROVAL_CHANNEL"),
    CONTRACT_UPDATE_CHANNEL("CONTRACT_UPDATE_CHANNEL"),
    SALARY_CREATE_OVERTIME_CHANNEL("SALARY_CREATE_OVERTIME_CHANNEL"),
    SALARY_UPDATE_OVERTIME_CHANNEL("SALARY_UPDATE_OVERTIME_CHANNEL"),
    SALARY_APPROVE_OVERTIME_CHANNEL("SALARY_APPROVE_OVERTIME_CHANNEL"),
    SALARY_CONFIRM_OVERTIME_CHANNEL("SALARY_CONFIRM_OVERTIME_CHANNEL"),
    SALARY_CREATE_LEAVE_CHANNEL("SALARY_CREATE_LEAVE_CHANNEL"),
    SALARY_UPDATE_LEAVE_CHANNEL("SALARY_UPDATE_LEAVE_CHANNEL"),
    SALARY_APPROVE_LEAVE_CHANNEL("SALARY_APPROVE_LEAVE_CHANNEL"),
    SALARY_CANCEL_LEAVE_CHANNEL("SALARY_CANCEL_LEAVE_CHANNEL"),
    SALARY_CONFIRM_LEAVE_CHANNEL("SALARY_CONFIRM_LEAVE_CHANNEL"),
    ASSIGN_CV_REVIEWER_CHANNEL("ASSIGN_CV_REVIEWER_CHANNEL"),
    DELETE_CV_REVIEWER_CHANNEL("DELETE_CV_REVIEWER_CHANNEL"),
    SAVE_CV_REVIEW_CHANNEL("SAVE_CV_REVIEW_CHANNEL"),
    SALARY_CREATE_WORKING_TIME_CHANNEL("SALARY_CREATE_WORKING_TIME_CHANNEL"),
    SALARY_UPDATE_WORKING_TIME_CHANNEL("SALARY_UPDATE_WORKING_TIME_CHANNEL"),
    SALARY_SEND_REQUEST_EDIT_WORKING_TIME_CHANNEL("SALARY_SEND_REQUEST_EDIT_WORKING_TIME_CHANNEL"),
    SALARY_CONFIRM_MAMY_REQUEST_EDIT_WORKING_TIME_CHANNEL("SALARY_CONFIRM_MAMY_REQUEST_EDIT_WORKING_TIME_CHANNEL"),
    SALARY_CREATE_WORK_OUTSIDE_CHANNEL("SALARY_CREATE_WORK_OUTSIDE_CHANNEL"),
    SALARY_UPDATE_WORK_OUTSIDE_CHANNEL("SALARY_UPDATE_WORK_OUTSIDE_CHANNEL"),
    SALARY_SEND_REQUEST_WORK_OUTSIDE_CHANNEL("SALARY_SEND_REQUEST_WORK_OUTSIDE_CHANNEL"),
    SALARY_CONFIRM_MANY_REQUEST_WORK_OUTSIDE_CHANNEL("SALARY_CONFIRM_MANY_REQUEST_WORK_OUTSIDE_CHANNEL"),
    RECRUITMENT_PROPOSAL_CREATE_CHANNEL("RECRUITMENT_PROPOSAL_CREATE_CHANNEL"),
    RECRUITMENT_DECISION_CREATE_CHANNEL("RECRUITMENT_DECISION_CREATE_CHANNEL");
    private final String code;

    ActionType(String code) {
        this.code = code;
    }

    @JsonCreator
    public static ActionType typeOfCode(String code) {
        return Arrays.stream(values()).filter(actionType -> actionType.code.equals(code)).findFirst()
                .orElseThrow(() -> new IllegalArgumentException("Unsupported action type code " + code));
    }

    @JsonValue
    private String toCode() {
        return code;
    }

}
